apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces
  - platform
  - apps
patches:
  - target:
      kind: Deployment
      name: ingress-nginx-controller
    path: patch-remove-ingress-ready.yaml
